### ISSUE TITLE
POST installation fails 

### ISSUE THREAD

**Issue by Naveen-LinuxAwsguy** [KiweeEu/magento2-on-kubernetes#158]
POST executing this script, getting the error, site not defined 
     

  # Update database schema if needed
          php bin/magento setup:db:status || php bin/magento setup:upgrade --keep-generated
          # Fail if database schema is not up-to-date after setup:upgrade
          php bin/magento setup:db:status
          # Import config if needed
          php bin/magento app:config:status || php bin/magento app:config:import
          # Fail if config is not up-to-date after app:config:import
          php bin/magento app:config:status
        envFrom:

![image](https://github.com/KiweeEu/magento2-on-kubernetes/assets/66349740/729d56a7-b84d-4baa-977a-ca27fec710f8)

**Comment by macieklewkowicz** [comment]
We'll need some more information to be able to reproduce this:

- which version of the manifests are you using?
- which version of the `kiweeteam/magento2` image are you using?
- did `magento-install` Job run successfully? (`kubectl logs job/magento-install`)
- are there any failed or pending pods? (`kubectl get pods`)
- was the Magento deployment able to start? (`kubectl logs deploy/magento-web -c setup`)
