### ISSUE TITLE
Trying to install magento enterprise edition

### ISSUE THREAD

**Issue by Naveen-LinuxAwsguy** [KiweeEu/magento2-on-kubernetes#218]
Trying to install magento enterprise edition with changes in cmposer.json & composer.lock, getting the below error in build phase 

<img width="946" alt="image" src="https://github.com/KiweeEu/magento2-on-kubernetes/assets/66349740/6243e883-a14e-459f-a2ce-e9b9a5783f78">

Please note I am using commerce version 2.4.6-p3, 

Below is directory structure of app files 

<img width="397" alt="image" src="https://github.com/KiweeEu/magento2-on-kubernetes/assets/66349740/85b5335f-fa9b-42b7-a56e-56d22a18d520">

**Comment by Naveen-LinuxAwsguy** [comment]
Thanks for the quick response, getting the below error

![image](https://github.com/KiweeEu/magento2-on-kubernetes/assets/66349740/cd7c3244-3bcb-46d3-a683-5f0499d50a09)

**Comment by macieklewkowicz** [comment]
Please double check your `app/etc/config.php`. A common cause for this error is that the `scopes` section of the config file is misconfigured or missing.

For testing try copying from https://github.com/KiweeEu/magento2-on-kubernetes/blob/2.4.6-p3-1/src/app/etc/config.php#L335-L392, but for an actual project build you'll need to dump the configuration from a running instance.

For more details see https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/deployment/technical-details.html?lang=en

**Comment by Naveen-LinuxAwsguy** [comment]
issue resolved
