### ISSUE TITLE
step-2/config/ingress.yaml might be unused

### ISSUE THREAD

**Issue by tidypol** [KiweeEu/magento2-on-kubernetes#221]
https://github.com/KiweeEu/magento2-on-kubernetes/blob/main/deploy/step-2/config/ingress.yaml

is it still used? i don't see it mentioned in any other part of the project (like in the yaml) so i guess is not applied and can be deleted.

**Comment by macieklewkowicz** [comment]
You're right, it's not used anymore.

This file is deleted in https://github.com/KiweeEu/magento2-on-kubernetes/pull/222.
