### ISSUE TITLE
Can you please le me know to enable www-data user to start cron-service 

### ISSUE THREAD

**Issue by Naveen-LinuxAwsguy** [KiweeEu/magento2-on-kubernetes#223]
Can you please le me know to enable www-data user to start cron-service , i tried many things it doesn't work is there any way

**Comment by macieklewkowicz** [comment]
Cron jobs are handled out-of-the-box by a Kubernetes [CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) configured in https://github.com/KiweeEu/magento2-on-kubernetes/blob/main/deploy/bases/app/cron/magento.yaml.

It runs `bin/magento cron:run` as `www-data` in a separate Pod every minute.

**Comment by Naveen-LinuxAwsguy** [comment]
issue resolved
