### ISSUE TITLE
db-0 crashloopbackoff

### ISSUE THREAD

**Issue by allamand** [KiweeEu/magento2-on-kubernetes#5]
Hi,

I was testing the solution but didn't manage to deploy the db.

This is the logs from the db-0 db container:

```
 k logs db-0 db -f -p 
Initializing database
2021-09-20T12:18:16.182042Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2021-09-20T12:18:16.182087Z 0 [ERROR] Aborting
```

I correctly delete pv and pvc prior to that but still have the same message.

testing this on AWS EKS cluster

**Comment by hoangnguyen3018** [comment]
Hi,

The same with @allamand although we have `--ignore-db-dir=lost+found` in the container args. Really need to help.

Thanks.

**Comment by allamand** [comment]
Hi if kubernetes is not mandatory for your need you can try running it on ECS https://github.com/allamand/cdk-magento-fargate
