### ISSUE TITLE
Question: Bad resquest 

### ISSUE THREAD

**Issue by fabiano-mallmann** [KiweeEu/magento2-on-kubernetes#6]
Hi, I'm trying to use this project, but I'm getting the following error when accessing index.php: 502 Bad Request
When I try to access some other file besides index.php (example: errors/503.php) it accesses normally, do you have any idea what it might be?

**Comment by tom00** [comment]
Hi,

There may be two problems:
1) Ingress can't reach Varnish
or
2) Varnish can't reach the NGINX web server.
Ideally if you inspect the logs of each by running `kubectl logs --tail=100 <pod-name>`.
